Fix README.md and use the correct Dockerfile for building
Running the currently mentioned:

./run os-image-stemcell-builder

will not work anymore and fails with:

ERROR:  Error installing rubygems-update:
        rubygems-update requires Ruby version >= 2.6.0.

Use the correct bionic based Dockerfile for building.