Fix spec: Bosh::Stemcell::Definition#== compares by value instead of reference
NOTE: This fixes a spec failure (re-)introduced in 527fdd1c and related to both 527fdd1c and 2108b483. However, it seems like this spec was probably already failing before 2108b483, too. The failure was undetected at the time as a result of issue #226.

See:
- 527fdd1c: Revert "Wip: remove centos, rhel, suse, photonos, trusty"
- 3c794ed1: Fix tests after reducing build targets
- https://github.com/cloudfoundry/bosh-linux-stemcell-builder/issues/226

Fixes spec failures:

```
ArgumentError: invalid operating system: not-ubuntu

  0) Bosh::Stemcell::Definition#== compares by value instead of reference
     Failure/Error: else raise ArgumentError.new("invalid operating system: #{operating_system_name}")

     ArgumentError:
       invalid operating system: not-ubuntu
     # ./lib/bosh/stemcell/operating_system.rb:9:in `for'
     # ./lib/bosh/stemcell/definition.rb:12:in `for'
     # ./spec/bosh/stemcell/definition_spec.rb:78:in `block (4 levels) in <module:Stemcell>'
     # ./spec/bosh/stemcell/definition_spec.rb:77:in `each'
     # ./spec/bosh/stemcell/definition_spec.rb:77:in `block (3 levels) in <module:Stemcell>'
```