Fix mkdir_p usage in Rakefile
Running download_os_image from the Rakefile like:

$ bundle exec rake stemcell:download_os_image[ubuntu,bionic]

currently fails with:

$ bundle exec rake stemcell:download_os_image[ubuntu,bionic]
Using OS image ubuntu-bionic
rake aborted!
ArgumentError: wrong number of arguments (given 2, expected 1)
/opt/bosh/Rakefile:51:in `block (2 levels) in <top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => stemcell:download_os_image

That's fixed with this commit.