🐞 Jammy deploys successfully on Azure
Prior to this commit, an attempt to deploy the beta Jammy stemcell v0.0.2 to
Azure would fail with an `OSProvisioningClientError` "... Failed to mount dvd
device...".

The failure was caused by an incompatibility with the Azure agent v2.2.53 and
Python 3.9. Specifically, the agent calls `array.array.tostring()` while
enumerating the network interfaces. This call was deprecated in Python 3.2, and
[removed](https://docs.python.org/3.9/library/array.html?highlight=array%20array%20tobytes#array.array.tobytes)
in 3.9.

The newest Azure agent v2.6.0.2 has been
[updated](https://github.com/Azure/WALinuxAgent/commit/1399bbe066070b034a51cac8d4c67c61a3ab9f29)
to be compatible with Python 3.9.

Although the failure seemed to indicate that the error was caused by an inability
to mount the DVD, that was not the case—the Azure agent mounted the DVD without
problems on its first run, only failing to mount the DVD after it crashed while
enumerating the network interfaces.

fixes, from `waagent.log`:
```
  File "/usr/local/lib/python3.9/dist-packages/azurelinuxagent/common/osutil/default.py", line 768, in _get_all_interfaces
    ifconf_buff = buff.tostring()
AttributeError: 'array.array' object has no attribute 'tostring'
, duration=0
2022-02-18T22:56:45.778758Z WARNING Daemon Daemon Daemon ended with exception -- Sleep 15 seconds and restart daemon
```
fixes, from `bosh deploy`:
```
OS Provisioning failure has reached terminal state and is non-recoverable for VM '1c9dddd6-42f4-45c6-88ab-3f920308bb8e'. Consider deleting and recreating this virtual machine. Also, make sure the image has been properly prepared (generalized).
...
Additional Details: OS Provisioning failed for VM '1c9dddd6-42f4-45c6-88ab-3f920308bb8e' due to an internal error: [ProtocolError] [CopyOvfEnv] Error mounting dvd: [OSUtilError] Failed to mount dvd device
```

[#221]