STIG V-38483, V-38476: base_rhel stage: Fixed the specs and code for STIG V-38483, V-38476. NOTE: Prior to 7d8674c4, the EPEL 8 GPG key was automatically imported (as shown in the log excerpt below). After 7d8674c4, that GPG key was NOT getting imported at all. Fixing the yum.conf templates to comply with the fixed STIG V-38483 spec also fixes the V-38476 failure.
Previous behavior log excerpt:

```
Extra Packages for Enterprise Linux 8 - x86_64  1.6 MB/s | 1.6 kB     00:00
Importing GPG key 0x2F86D6A1:
 Userid     : "Fedora EPEL (8) <epel@fedoraproject.org>"
 Fingerprint: 94E2 79EB 8D8F 25B2 1810 ADF1 21EA 45AB 2F86 D6A1
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-8
```

See:
- 7d8674c4: base_rhel, base_centos_packages stages: Call the RHSM commands BEFORE the `yum -c ... groupinstall ...` commands.

Fixes/resolves the following spec failures:

```
  507) RHEL 8 OS image official Red Hat gpg key is installed (stig: V-38476) rpm -qa gpg-pubkey* 2>/dev/null | xargs rpm -qi 2>/dev/null shows the Fedora EPEL 8 key is installed
       Failure/Error: it('shows the Fedora EPEL 8 key is installed') { expect(subject.stdout).to include('Fedora EPEL (8) <epel@fedoraproject.org>') }

         expected "Name        : gpg-pubkey\nVersion     : fd431d51\nRelease     : 4ae0493b\nArchitecture: (none)\nInst...v+SQnM20c0pdOXAq9GKKhi\nvt61kpkXoRGxjTlc6h+69aidSg==\n=ls8J\n-----END PGP PUBLIC KEY BLOCK-----\n\n" to include "Fedora EPEL (8) <epel@fedoraproject.org>"
         Diff:
         @@ -1,114 +1,227 @@
         -Fedora EPEL (8) <epel@fedoraproject.org>
         +Name        : gpg-pubkey
...
         +-----END PGP PUBLIC KEY BLOCK-----
       # ./spec/os_image/rhel_8_spec.rb:684:in `block (4 levels) in <top (required)>'
```

Fixes/resolves the following errors:

```
+ rpm --import /mnt/stemcells/null/null/rhel/build/build/stages/base_rhel/assets/RPM-GPG-KEY-RHEL-8-auxiliary
error: /mnt/stemcells/null/null/rhel/build/build/stages/base_rhel/assets/RPM-GPG-KEY-RHEL-8-auxiliary: key 1 not an armored public key.
=== You can resume_from the 'base_rhel' stage by using resume_from=base_rhel ===
```

```
You have enabled checking of packages via GPG keys. This is a good thing.
However, you do not have any GPG public keys installed. You need to download
the keys for packages you wish to install and install them.
You can do that by running the command:
    rpm --import public.gpg.key

Alternatively you can specify the url to the key you would like to use
for a repository in the 'gpgkey' option in a repository section and yum
will install it for you.

For more information contact your distribution or package provider.

Problem repository: base
=== You can resume_from the 'base_rhel' stage by using resume_from=base_rhel ===
```